// Static program content: week themes and the task pools each week's
// days are filled from. Cycled deterministically across the 12-week block.

export const TOTAL_WEEKS = 12;

export const WEEK_THEMES: Record<number, string> = {
  1: "ARRAYS · STRINGS · HASHING",
  2: "TWO POINTERS · SLIDING WINDOW",
  3: "STACKS · QUEUES · LINKED LISTS",
  4: "TREES · BINARY SEARCH TREES",
  5: "HEAPS · PRIORITY QUEUES",
  6: "GRAPHS I · BFS/DFS",
  7: "GRAPHS · CONCURRENCY · CACHING",
  8: "DYNAMIC PROGRAMMING I",
  9: "DYNAMIC PROGRAMMING II · BACKTRACKING",
  10: "GREEDY · INTERVALS · BIT TRICKS",
  11: "TRIES · ADVANCED STRUCTURES · MOCK BLITZ",
  12: "SYSTEM DESIGN CAPSTONE · FULL MOCKS",
};

export const DSA_POOL: string[] = [
  "LC 1 · Two Sum",
  "LC 121 · Best Time to Buy and Sell Stock",
  "LC 217 · Contains Duplicate",
  "LC 238 · Product of Array Except Self",
  "LC 53 · Maximum Subarray",
  "LC 56 · Merge Intervals",
  "LC 57 · Insert Interval",
  "LC 15 · 3Sum",
  "LC 11 · Container With Most Water",
  "LC 3 · Longest Substring Without Repeating Characters",
  "LC 49 · Group Anagrams",
  "LC 242 · Valid Anagram",
  "LC 14 · Longest Common Prefix",
  "LC 189 · Rotate Array",
  "LC 54 · Spiral Matrix",
  "LC 73 · Set Matrix Zeroes",
  "LC 125 · Valid Palindrome",
  "LC 42 · Trapping Rain Water",
  "LC 76 · Minimum Window Substring",
  "LC 424 · Longest Repeating Character Replacement",
  "LC 167 · Two Sum II — Sorted Array",
  "LC 18 · 4Sum",
  "LC 75 · Sort Colors",
  "LC 560 · Subarray Sum Equals K",
  "LC 128 · Longest Consecutive Sequence",
  "LC 347 · Top K Frequent Elements",
  "LC 20 · Valid Parentheses",
  "LC 155 · Min Stack",
  "LC 150 · Evaluate Reverse Polish Notation",
  "LC 739 · Daily Temperatures",
  "LC 496 · Next Greater Element I",
  "LC 239 · Sliding Window Maximum",
  "LC 232 · Implement Queue using Stacks",
  "LC 227 · Basic Calculator II",
  "LC 394 · Decode String",
  "LC 206 · Reverse Linked List",
  "LC 21 · Merge Two Sorted Lists",
  "LC 141 · Linked List Cycle",
  "LC 19 · Remove Nth Node From End of List",
  "LC 2 · Add Two Numbers",
  "LC 138 · Copy List with Random Pointer",
  "LC 143 · Reorder List",
  "LC 23 · Merge k Sorted Lists",
  "LC 104 · Maximum Depth of Binary Tree",
  "LC 98 · Validate Binary Search Tree",
  "LC 101 · Symmetric Tree",
  "LC 102 · Binary Tree Level Order Traversal",
  "LC 236 · Lowest Common Ancestor of a Binary Tree",
  "LC 199 · Binary Tree Right Side View",
  "LC 105 · Construct Binary Tree from Preorder and Inorder",
  "LC 230 · Kth Smallest Element in a BST",
  "LC 297 · Serialize and Deserialize Binary Tree",
  "LC 124 · Binary Tree Maximum Path Sum",
  "LC 215 · Kth Largest Element in an Array",
  "LC 295 · Find Median from Data Stream",
  "LC 621 · Task Scheduler",
  "LC 973 · K Closest Points to Origin",
  "LC 200 · Number of Islands",
  "LC 133 · Clone Graph",
  "LC 207 · Course Schedule",
  "LC 210 · Course Schedule II",
  "LC 417 · Pacific Atlantic Water Flow",
  "LC 127 · Word Ladder",
  "LC 743 · Network Delay Time",
  "LC 684 · Redundant Connection",
  "LC 261 · Graph Valid Tree",
  "LC 787 · Cheapest Flights Within K Stops",
  "LC 994 · Rotting Oranges",
  "LC 1091 · Shortest Path in Binary Matrix",
  "LC 70 · Climbing Stairs",
  "LC 198 · House Robber",
  "LC 213 · House Robber II",
  "LC 300 · Longest Increasing Subsequence",
  "LC 322 · Coin Change",
  "LC 139 · Word Break",
  "LC 377 · Combination Sum IV",
  "LC 91 · Decode Ways",
  "LC 62 · Unique Paths",
  "LC 55 · Jump Game",
  "LC 45 · Jump Game II",
  "LC 416 · Partition Equal Subset Sum",
  "LC 1143 · Longest Common Subsequence",
  "LC 72 · Edit Distance",
  "LC 152 · Maximum Product Subarray",
  "LC 647 · Palindromic Substrings",
  "LC 5 · Longest Palindromic Substring",
  "LC 309 · Best Time to Buy/Sell Stock with Cooldown",
  "LC 494 · Target Sum",
  "LC 78 · Subsets",
  "LC 46 · Permutations",
  "LC 39 · Combination Sum",
  "LC 79 · Word Search",
  "LC 131 · Palindrome Partitioning",
  "LC 51 · N-Queens",
  "LC 17 · Letter Combinations of a Phone Number",
  "LC 22 · Generate Parentheses",
  "LC 134 · Gas Station",
  "LC 435 · Non-overlapping Intervals",
  "LC 253 · Meeting Rooms II",
  "LC 136 · Single Number",
  "LC 191 · Number of 1 Bits",
  "LC 338 · Counting Bits",
  "LC 371 · Sum of Two Integers",
  "LC 190 · Reverse Bits",
  "LC 268 · Missing Number",
  "LC 208 · Implement Trie (Prefix Tree)",
  "LC 212 · Word Search II",
  "LC 211 · Design Add and Search Words Data Structure",
  "LC 146 · LRU Cache",
  "LC 460 · LFU Cache",
  "LC 355 · Design Twitter",
  "LC 528 · Random Pick with Weight",
  "LC 380 · Insert Delete GetRandom O(1)",
  "LC 480 · Sliding Window Median",
  "LC 407 · Trapping Rain Water II",
  "LC 126 · Word Ladder II",
  "LC 4 · Median of Two Sorted Arrays",
  "LC 10 · Regular Expression Matching",
  "LC 44 · Wildcard Matching",
];

export const LLD_POOL: string[] = [
  "Design a parking lot — class diagram + concurrency notes",
  "Design an elevator system — state machine + scheduling policy",
  "Design a URL shortener — hashing + collision strategy",
  "Design a rate limiter — token bucket vs sliding window",
  "Design a vending machine — state pattern",
  "Design a tic-tac-toe engine — win detection strategy",
  "Design a library management system — checkout/reservation flow",
  "Design a chess engine — move validation + board representation",
  "Design a notification system — observer pattern, channels",
  "Design a ride-sharing dispatch — matching algorithm",
  "Design a movie ticket booking system — seat locking + concurrency",
  "Design a restaurant reservation system — time-slot conflicts",
  "Design a logging framework — thread-safe writers",
  "Design an in-memory file system — trie-based paths",
  "Design a splitwise-style expense tracker — debt simplification",
  "Design an ATM — transaction state machine",
  "Design a text editor — undo/redo with command pattern",
  "Design a snake game — collision + growth logic",
  "Design a hotel booking system — inventory + overbooking rules",
  "Design a car rental system — availability + pricing",
  "Design an in-memory key-value store — TTL + eviction",
  "Design a job scheduler — priority queue + retries",
  "Design a single-node social feed — fan-out on write vs read",
  "Design a traffic light controller — concurrency across intersections",
];

export const HLD_POOL: string[] = [
  "Spanner paper, §4 — notes on TrueTime and commit wait",
  "Dynamo paper — consistent hashing + vector clocks",
  "Kafka internals — log segments and ISR replication",
  "Design a URL shortener at scale — sharding + cache tier",
  "Design a rate limiter at scale — distributed token buckets",
  "Design a news feed system — fan-out on write vs read tradeoffs",
  "Design a chat system — message ordering + delivery guarantees",
  "Design a search autocomplete — trie + ranking service",
  "Design a video streaming service — CDN + adaptive bitrate",
  "Design a distributed cache — consistent hashing ring",
  "CAP theorem deep dive — partition tolerance tradeoffs",
  "Design a web crawler — politeness + dedup at scale",
  "Design a payment system — idempotency + double-entry ledger",
  "Design a notification delivery system — fan-out + retries",
  "Raft paper — leader election and log replication",
  "Design a ticketing/inventory system — overselling prevention",
  "Design a metrics pipeline — time-series storage",
  "Design a distributed job queue — at-least-once delivery",
  "Design a multi-tenant API gateway — quota + throttling",
  "Bigtable paper — SSTables and compaction",
  "Design a proximity/location service — geohashing",
  "Design a collaborative document editor — operational transforms",
  "Design an ad click aggregation system — exactly-once counting",
  "Design a global load balancer — anycast + health checks",
];

export const MOCK_POOL: string[] = [
  'Peer mock — "Design a URL shortener"',
  'Peer mock — "Design a rate limiter"',
  'Peer mock — "Design a parking lot"',
  'Peer mock — "Design a chat system"',
  'Peer mock — "Design a news feed"',
  'Peer mock — "Design an elevator system"',
  'Peer mock — "Design a ride-sharing dispatch"',
  "Coding round — mixed two-pointer + DP set",
  'Peer mock — "Design a distributed cache"',
  "Coding round — mixed graph + heap set",
  'Peer mock — "Design a video streaming service"',
  "Full-loop dry run — coding + design + behavioral",
];

export const REVIEW_POOL: string[] = [
  "Review missed problems from the week — redo under time pressure",
  "Spaced repetition — resurface week's flagged cards",
  "Mock interview post-mortem — rewrite weak answers",
  "Re-derive time/space complexity for the week's top 5 problems",
  "Behavioral story bank — refine 2 STAR stories",
  "Full week retro — update weak-topic list for next block",
];

// Known categories keep their original design colors; anything else (a
// custom category from an imported roadmap) gets a deterministic color
// from the fallback palette below, so the same label always renders the
// same color without persisting a color assignment anywhere.
const KNOWN_CATEGORY_COLOR: Record<string, string> = {
  DSA: "#3FC7B4",
  LLD: "#FF7A85",
  HLD: "#A78BFA",
  MOCK: "#5B9DFF",
  REVIEW: "#F5A524",
};

const FALLBACK_PALETTE: string[] = [
  "#F5A524", "#5B9DFF", "#3FC7B4", "#FF7A85", "#A78BFA",
  "#4ADE80", "#FB923C", "#38BDF8", "#F472B6", "#C084FC",
];

/** Stable palette for the built-in interview-prep categories. */
export const CATEGORY_COLOR = KNOWN_CATEGORY_COLOR;

export function colorForCategory(category: string): string {
  const key = category.trim().toUpperCase();
  if (KNOWN_CATEGORY_COLOR[key]) return KNOWN_CATEGORY_COLOR[key];
  let hash = 0;
  for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) | 0;
  return FALLBACK_PALETTE[Math.abs(hash) % FALLBACK_PALETTE.length];
}
